### ISSUE TITLE
Error: no auth mechanism defined

### ISSUE THREAD

**Issue by frankgreco** [apigee/microgateway-config#12]
I cloned the project and then did `npm test` and got the error, `Error: no auth mechanism defined`. This is because the `edge_micro.bootstrap` url requires authentication. Is this the expected behavior. If so, how to I run tests locally?

**Comment by mdobson** [comment]
Hi @frankgreco,

You'll want to set your edgemicro key and secret as the following environment variables:

- `EDGEMICRO_KEY`
- `EDGEMICRO_SECRET`

Our tests require those credentials to talk with edge services. Apologies for the lack of documentation around this. I'll get that updated ASAP.

**Comment by mdobson** [comment]
Oh. You'll also need to update this line in the tests to point at your personal config: 

https://github.com/apigee/microgateway-config/blob/master/tests/it.js#L32

**Comment by frankgreco** [comment]
@mdobson do you have an abstract/generic config that can be used to test against so I don't have to use my own. I will be making a pull request shortly and am just trying to test my small change before I do that. I shouldn't have to test against my custom config to test a change that would potentially be in master.

**Comment by mdobson** [comment]
Option 1 isn't feasible. As this is a base URL for interacting with Apigee services. Making this unauthenticated would not be a good idea.

Option 2 sounds great. Look forward to your pull request.

-Matt

**Comment by frankgreco** [comment]
@mdobson just made my pull request. Part of it will resolve this issue

**Comment by mdobson** [comment]
Great. I'll review accordingly.
